### ISSUE TITLE
US-10: Secret file mount path

### ISSUE THREAD

**Issue by alexkalish** [cyberark/secrets-provider-for-k8s#337]
## User Story

**As a** application developer 
**I want** to configure the mount path used for the volume containing secret files 
**So that** to configure the mount path used for the volume containing secret files 

* To start, this is met by asking the user to add a “volumeMount” on the app container, as there no way to inject this without an admission controller.  

### Test Scenarios

*If desired, add one or more test scenarios required for user story acceptance.
Ideally, they are executed by automated tests. For more details on Gerkin syntax,
see this [article](https://cucumber.io/docs/gherkin/reference/)*

**Given** <this setup/context>
**When** <an action/event occurs>
**Then** <the expected behavior/outcome>

### Implementation Tasks

*The following issues have been created to implement this user story:*

* <issue link>

**Comment by diverdane** [comment]
@alexkalish , can you elaborate on what the DoD would be for this? Is it sufficient to simply document how a developer would add a `volumeMount` definition to their manifest? I'm not sure what else we can do here, since they'll want to choose their `volumeMount` path (i.e. we can't provide a static YAML snippet).

**Comment by alexkalish** [comment]
Yes, I added this mostly for the sake of completeness and visibility.  I realize that there may not be any implementation tasks.  So, it's fine so say this is accomplished by docs.
