### ISSUE TITLE
Update Readme with envrionment variables needed for the init container

### ISSUE THREAD

**Issue by andresguisado** [cyberark/secrets-provider-for-k8s#92]
Update the readme mentioning the environment variables needed for the init container for people having issues with Conjur/DAP authenticaton.

An good example could be the one in [kubernetes authenticator docker hub](https://hub.docker.com/r/cyberark/conjur-kubernetes-authenticator):

![Screenshot 2020-05-21 at 16 45 37](https://user-images.githubusercontent.com/13769361/82577189-8bb26700-9b82-11ea-81b8-36397cbeeb79.png)

You might want to update [docker hub](https://hub.docker.com/r/cyberark/secrets-provider-for-k8s) as well.

**Comment by orenbm** [comment]
Thanks @andresguisado for raising this :)

I've added this ticket to our R&D Boost. Hopefully it will be addressed in the next few weeks.

**Comment by Tovli** [comment]
@andresguisado - As we have this info in the [official docs](https://docs.conjur.org/Latest/en/Content/Integrations/Kubernetes_deployApplicationsConjur-k8s-Secrets.htm?tocpath=Integrations%7COpenShift%252C%20Kubernetes%252C%20and%20GKE%7CDeploy%20Applications%7C_____3#Step4AddtheCyberArkSecretsProviderforKubernetesimagetotheapplicationdeploymentmanifest)

Can you advise what would be a good experience for you where we wouldn't need to have a second source of truth for this information?

**Comment by izgeri** [comment]
@Tovli please note that we're working with our technical writers on an official best practice for open source documentation, and so far we're leaning toward putting usage documentation in GitHub READMEs unless it's complex enough to merit being documented on the website.

Even if the project does reach that level of complexity (which this one does), some basic usage information will still always need to be included in GitHub because it's common to visit the public repository of the project for guidance in the course of using it.

In this case, I'd suggest that if this table (and all configuration info) is fully documented in our docs, we should maybe remove the table from the README but be sure to clearly link to the relevant documentation page for further reading.

It would also be reasonable to decide that the repo maintains the table in the README, and we have the extra burden of a second source of truth to maintain in the docs but the community benefit of guidelines right where the project lives.

I'm fine with either path, but whichever we choose to follow here I think we should resolve this issue soon.

**Comment by Tovli** [comment]
Thanks @izgeri . Having unified standards will be the best option by me.
I do think we need to discuss and try to have one source of truth that both our docs and README will get info from. This should give the best experience for the users of our repos

Following your comment I think we should start with putting a link to the docs and once the standards are ready we should re-examine and consider how to proceed
